### ISSUE TITLE
anac2019_std world config bug

### ISSUE THREAD

**Issue by cobygithub** [yasserfarouk/negmas#3]
Hello,

I'd like to extend the anac2019_std tournament deadline and for that purpose, set total_time_out to 72000, but it appears that it still considers the default parameter 7200 and the tournament finishes in two hours, I've found that anac_2019_config_generator in scml.utils always assigns total_time_out to 7200 which may be potentially the cause of the bug.

**Comment by yasserfarouk** [comment]
There are two different time-limits here:
1. time_limit parameter of the world constructor. This specifies the time limit for any single world simulation. That was fixed to 7200 (it is 7200 + 3600 in the last commit). This is a fixed parameter as it is a part of the published specs of ANAC 2019 SCML.
2. total_timeout which is a parameter of the tournament() function. This is the total time allowed for the whole tournament. Currently it is set to None == infinity.

If you would like to extend the time out for each individual world, you have to create a new config_generator function similar to anac2019_config_generator that changes this parameter. We are not allowing it to change in anac2019_config_generator because this number is a part of the specs for the league this year.

I hope this helped.
2. total_time_out that is the total time-out for the whole tournament.

**Comment by cobygithub** [comment]
OK, thank you. I've created a custom config_generator and it's working.

**Comment by yasserfarouk** [comment]
Great. I will close this issue :-)
